spring:
  profiles:
    active:
      - dev
---

server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml   #mybatis配置文件所在路劲
  type-aliases-package: com.wcsg.springcloud.entites        #实体别名
  mapper-locations: classpath:mybatis/mapper/**/*.xml     #mapper映射路劲

spring:
  profiles: dev
  application:
    name: microsevicecloud-user                           #对外的微服务名字不能使用下划线）
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/clouddb
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                       #数据库连接池最小维持连接数
      initial-size: 5                                   #初始化连接数
      max-total: 5                                      #最大连接数
      max-wait-millis: 200                             #等待链接最大时间

eureka:
 client:
    serviceUrl:
      defaultZone: http://wcsg1:7001/eureka,http://wcsg2:7002/eureka
    instance:
      instance-id: microsevicecloud-8001   #自定义hystrix服务名称
      prefer-ip-address: true   #显示地址ip

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /

#配置info信息
info:
    app.name: wcsg-springcloud
    company.name: www.wcsg.com
    build.artifactId: $project.artifactId$
    build.version: $project.version$

    
---

server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml   #mybatis配置文件所在路劲
  type-aliases-package: com.wcsg.springcloud.entites        #实体别名
  mapper-locations: classpath:mybatis/mapper/**/*.xml     #mapper映射路劲

spring:
  profiles: test
  application:
    name: microsevicecloud-user                           #对外的微服务名字不能使用下划线）
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/clouddb1
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                       #数据库连接池最小维持连接数
      initial-size: 5                                   #初始化连接数
      max-total: 5                                      #最大连接数
      max-wait-millis: 200                             #等待链接最大时间

eureka:
 client:
    serviceUrl:
      defaultZone: http://wcsg1:7001/eureka,http://wcsg2:7002/eureka
    instance:
      instance-id: microsevicecloud-8001   #自定义hystrix服务名称
      prefer-ip-address: true   #显示地址ip

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /

#配置info信息
info:
    app.name: wcsg-springcloud
    company.name: www.wcsg.com
    build.artifactId: $project.artifactId$
    build.version: $project.version$
